name: Terraform Apply

on:
  push:
    branches: [ "master" ]
jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_AD_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      
      - name: Terraform Initialize
        id: init
        run: |
          terraform init
      
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          
      
